// category list to be shared with add and edit event pages
export const categoryList = [
  'Animals',
  'Art',
  'Baseball',
  'Beach',
  'Billiards',
  'Bowling',
  'Cooking',
  'Dancing',
  'Exercise',
  'Fishing',
  'Food',
  'Football',
  'Geocaching',
  'Golfing',
  'Martial Arts',
  'Movies',
  'Music',
  'Photography',
  'Programming',
  'Running',
  'Shopping',
  'Singing',
  'Skateboarding',
  'Soccer',
  'Sports',
  'Surfing',
  'Swimming',
  'Tennis',
  'Video Games',
  'Volleyball',
  'Weightlifting',
  'Yoga',
];