// organization list to be shared with add and edit event pages
export const organizationList = [
  'Academy of Creative Media Student Association',
  'Accounting Club',
  'AECT-Hawai\'I',
  'ALPHA: Association of Leaders, Philanthropists, and Hawaiian Activists',
  'American Assembly For Men in Nursing',
  'American Cetacean Society Student Coalition',
  'American Indian Science & Engineering Society',
  'American Institute of Architecture Students Hawaii Chapter',
  'American Library Association Student Chapter',
  'American Marketing Association',
  'American Society of Civil Engineers',
  'American Society of Heating, Refrigeration, and Air Conditioning Engineers',
  'American Society of Mechnical Engineers',
  'Anthropology Graduate Student Association',
  'Anthropology Undergraduate Student Association',
  'Art Club',
  'Asian-Pacific Law & Policy Journal',
  'Association for Computing Machinery at Manoa',
  'Bachelor of Social Work Organization',
  'Beta Alpha Psi-Delta Theta Chapter',
  'Biological Engineering Student Association',
  'Black Law Students Association',
  'Botanical Society of America Student Chapter at U.H.M.',
  'Business Executive Society of Tomorrow',
  'Business of Medicine Interest Group',
  'Chemistry Club at the University of Hawaii at Manoa',
  'Chi Epsilon',
  'Citizen\'s Climate Lobby-UH Manoa',
  'Club Managers Association of America POP Student Chapter',
  'Coral Reef Restoration Project at the University of Hawaii',
  'CTAHR Student Ambassadors',
  'Debate and Forensics Society',
  'Delta Sigma Pi Rho Chi',
  'Disney Ohana Club',
  'East-West Toastmasters',
  'Engineering Ohana',
  'Engineer\'s Council at University of Hawaii',
  'Eta Kappa Nu',
  'Eta Sigma Delta',
  'Ethnic Studies Student Association',
  'Ethnobiology Society',
  'Family Medicine Interest Group',
  'Financial Management Association',
  'Food Science and Human Nutrition Council',
  'Formula SAE Rainbow Warrior Racing',
  'Friends of the Family',
  'Geography Club at UH Manoa',
  'Geology & Geophysics Club',
  'Graduate Art Council',
  'Graduate Business Student Association',
  'Graduate Student Sociological Association',
  'Graduate Women In Science Hawaii Chapter',
  'Hawai\'I Educational Research Association',
  'Hawaii Student Entrepreneurs',
  'Health Occupation Student Association at UHM',
  'Higher Education Student Association',
  'Horticultral Society',
  'Hui Dui',
  'Hui Ola Pono',
  'Human Rights Association',
  'Ilima SACNAS Chapter at the University of Hawai\'I',
  'Information Technology Management Association',
  'Innovators of Fashion',
  'Institute of Electrical and Electronics Engineers',
  'Inter-Business Council',
  'International Business Organization',
  'International Student Association',
  'JABSOM Patient Safety and Quality Improvement Interest Group',
  'JABSOM Primary Care Progress at UH',
  'JABSOM Research Interest Group',
  'Ka Lama Kukui Indigenous Student Interest Group',
  'Ke Koa Ekola O Ke Alahele',
  'KOKUA Connection',
  'KRS Club at the University of Hawai‘i at M?noa',
  'LAMBDA Law Student Association',
  'Lambda Pi Eta - Omega Upsilon Chapter',
  'Language Documentation Training Center',
  'Linguistic Society of Hawaii',
  'Love Your Melon',
  'Manoa Astronomical Technologies',
  'Manoa International Relations Association',
  'Manoa Pre-Law Association',
  'Marine Robotics at the University of Hawaii',
  'Medical Education Student Interest Group',
  'Medical Student Mentorship Program',
  'Model United Nations at UHM',
  'Myron B. Thompson School of Social Work Graduate Student Organization',
  'Na Hawaii Imi Loa',
  'National Student Speech Language Hearing Association',
  'Native American Law Student Association, Hawaii Chapter',
  'Natural Resources and Environmental Management GSO',
  'Online Learning, Technologoy, & Teaching Professionals',
  'Pacific Asia Travel Association',
  'Partners in Health Engage',
  'Partnership for Social Justice',
  'Pens & Friends',
  'Phi Alpha Honor Society Nu Sigma',
  'Phi Alpha Theta (Alpha Beta Epsilon)',
  'Philosophy Students Association',
  'Pi Tau Sigma',
  'Pre-Dental Association',
  'PreMedical Association',
  'Pre-Pharmacy Association',
  'Pre-Veterianry Club at the University of Hawaii',
  'Professional Development Organizing Committee',
  'Psi Sigma: The Psychology Connection',
  'Public Administration Student Organization',
  'Public Relations Student Society of America',
  'Regents and Presidential Scholars',
  'Right to Research Coalition at the Univeristy of Hawaii',
  'Rural Health Interest Group',
  'Science Communicators ‘ohana',
  'Second Language Studies Student Association',
  'Silver Wings',
  'Social Leaders at Manoa',
  'Society for Collegiate Leadership & Achievement',
  'Society for Conservation Biology',
  'Society for Human Resources Management',
  'Society for Tropical Medicine and Global Health (Trop Med Interest Group)',
  'Society of American Archivists (Student Chapter)',
  'Society of Automotive Engineers',
  'Society of Physics Students at the University of Hawaii at Manoa',
  'Society of Women Engineers',
  'Sociological Society at UH Manoa',
  'Special Libraries Association - Student Chapter',
  'Speech Communication Society',
  'Spoon University at the University of Hawaii at Manoa',
  'Student Immunization Initiative',
  'Student Nurse Association',
  'Students in Pathology at John A. Burns School of Medicine',
  'Travel Industry Management Student Association',
  'Tropical Plant & Soil Sciences Graduate Student Organization',
  'University Students of Urban and Regional Planning',
  'Victoria\'s Secret PINK',
  'Wilderness Medicine Interest Group',
  'Women\'s Interest Group (JABSOM)',
  'World of Good',
  'Black Student Association',
  'Chinese Friends (Zhongwen Pengyou)',
  'Chinese Students & Scholars Association of UH Manoa',
  'Ethnomusicology Association',
  'Fealofani O Samoa',
  'German Club at the University of Hawaii',
  'Hanwoori',
  'Hui Aloha \'Aina Tuahine',
  'Hui Malama Honua',
  'Islamic Society at University of Hawaii at Manoa',
  'Japanese Culture Club at UH Manoa',
  'Katipunan Club',
  'Korean Student Association',
  'La Raza Unida at UH Manoa',
  'LOTUS - UH',
  'Lovers of South Asian Cultures',
  'Marianas Club at UH Manoa',
  'Micronesia Connections',
  'Nongkrong Yuk! Indonesian Club',
  'Okinawa Culture Club',
  'Pacific Advocates Peoples Association',
  'Russian Cuture Club',
  'Society of Nepalese in Hawaii',
  'Tahiti Club',
  'Taiwanese Student Association',
  'Thai Studies Club',
  'Timpuyog Organization',
  'Tinumasalasala A Samoa Student Organization',
  'Vietnamese Student Organization at UH Manoa',
  'Wai\'anapanapa',
  'Wushu Club',
  'Alpha Gamma Delta',
  'Tau Kappa Epsilon',
  'Beta Beta Gamma Sorority',
  'Inter-Greek Council',
  'Kappa Sigma',
  'National Panhellenic Conference',
  'Phi Mu',
  'Golden Key International Honour Society',
  'Honors Student Organization',
  'Mortar Board National Honor Society Hui Po\'okela Chapter',
  'National Society of Collegiate Scholars',
  'Psi Chi',
  'Aloha Table Top',
  'Anime and Manga Society',
  'Campus Drummers',
  'Contra Dancers of the University of Hawaii',
  'Ete Bowl',
  'Freedom Dance Movement',
  'Freestyle Dance Club',
  'Glass Art Family',
  'Golf Club at the University of Hawaii at Manoa',
  'Hawaii African Dance + Drum Club',
  'Internal Martial Arts Clubs at UHM',
  'League of Legends Club at UH Manoa',
  'Movement Research',
  'Parkour Club',
  'Phoenix \\Im/Dance Club',
  'Phoenix Dance Chamber',
  'Playroll',
  'Queen Nicki Minaj Fanclub',
  'Rainbow Jugglers Juggling Club',
  'Salsa Dancing at UHM',
  'Smash Bros. Club at the University of Hawaii at Manoa',
  'Theatre and Dance Association',
  'Waikiki Acrobatic Troupe',
  'Daniel K. Inouye Leaders in Action',
  'Planned Parenthood Generation Action',
  'Revolution Book Club',
  'Student Alliance for Animals',
  'Sustainable Food-Choice Alliance',
  'Young Americans for Liberty',
  'Young Progessives Demanding Action',
  'Aloha NAVS',
  'Baha\'i Association at UH Manoa',
  'Baptist Collegiate Ministries',
  'Campus Chinese Christian Fellowship',
  'CARP Hawaii',
  'Church in Honolulu',
  'Cru',
  'Every Nation Campus - Pearlside',
  'Every Nation Campus Honolulu',
  'Falun Gong Club',
  'Hawaii Chinese Baptist Church College Fellowship',
  'Hillel Hawaii',
  'Intervarsity Christian Fellowship',
  'Jehovah\'s Witnesses at the University of Hawaii - Manoa',
  'Latter-Day Saint Student Association',
  'Living Stone Chinese Christian Fellowship',
  'Living Water Fellowship',
  'Mind Above',
  'Na Koa',
  'Newman Center (Catholic Campus Ministry)',
  'Reaching Our Campus Ministries',
  'Remix Club at the University of Hawaii at Manoa',
  'Transcendental Meditation Club',
  'Transformational Community',
  'Tzu Chi Collegiate Association',
  'UPENA',
  'Wesley Foundation',
  'Young Life',
  'AlohaThon Dance Marathon',
  'Alpha Phi Omega',
  'Atherton YMCA',
  'Best Buddies - Hawaii',
  'Circle K International',
  'Lifesavers Club at UH Manoa',
  'Pueo Library',
  'Rotaract Club at the University of Hawai\'I at Manoa',
  'S-Cubed',
  'Surfrider Foundation at University of Hawai\'I at Manoa',
  'That Sandwich Club',
  'Volunteers for Intercultural and Definitive Adventures',
  'Aikido @ UHM',
  'Alohamoras at UH Manoa',
  'Brazilian Freestyle Jiu-Jitsu',
  'Capoeira Senzala',
  'Cycle Manoa',
  'Hawaii Shotokan Karate',
  'Judo Team at the University of Hawaii',
  'Kempo Club at UHM',
  'Kim\'s Tae Kwon Do at UHM',
  'Koko',
  'Laupahoehoe School of Thai Arts',
  'Manoa Martial Arts Coalition',
  'Table Tennis Club',
  'Water Polo Club',
  'Arnold Air Society',
  'Breathe Aloha',
  'Colleges Against Cancer',
  'COP Alakaina Club',
  'Financial Literacy Program at Manoa',
  'Hawaii Undergraduate Initiative',
  'Health Careers Opportunity Program',
  'Ka Mea Kolo',
  'LGBTea Time',
  'Manoa Peer Advisers',
  'Manoa Sophomore Experience',
  'Peer Mentor Ohana',
  'Resident Assistant Council',
  'Student Veterans Organization at UH Manoa'];
